// auto-generated
// Code generated by '$ fyne bundle'. DO NOT EDIT.

package main

import (
	_ "embed"
	"fyne.io/fyne/v2"
)

//go:embed queen.png
var resourceQueenPngData []byte
var resourceQueenPng = &fyne.StaticResource{
	StaticName:    "queen.png",
	StaticContent: resourceQueenPngData,
}
